# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.12'
  inputs:
    versionSpec: '3.12'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

- script: |
    python -m playwright install
  displayName: 'Install Playwright Browsers'

- script: |
    mkdir -p reports
    pytest \
      --junitxml=reports/results.xml \
      --html=reports/report.html \
      --self-contained-html
  displayName: Run Playwright Tests
  env:
    HEADLESS: "true"
    BASE_URL: "https://the-internet.herokuapp.com/"

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'reports/results.xml'
    failTaskOnFailedTests: true

- task: PublishPipelineArtifact@1
  displayName: Publish HTML Report
  inputs:
    targetPath: 'reports'
    artifact: 'TestReports'    